#ifndef BACCABLE_STORAGE_FLASH_LAYOUT_H
#define BACCABLE_STORAGE_FLASH_LAYOUT_H
#include <stdbool.h>
#include <stdint.h>
#define STORAGE_PAGE_SIZE 2048U
#define STORAGE_FLASH_END 0x08020000U
#define STORAGE_RECORDS_START 0x0801d000U
#define USB_FLASH_START_ADDRESS 0x08010000U
#define TOTAL_USB_DEVICE_SIZE (STORAGE_RECORDS_START - USB_FLASH_START_ADDRESS)
#define STORAGE_SECTOR_SIZE 512U
#define STORAGE_SECTOR_COUNT (TOTAL_USB_DEVICE_SIZE / STORAGE_SECTOR_SIZE)
static inline bool storage_sector_range(uint32_t sector, uint32_t count) {
    return count > 0 && sector < STORAGE_SECTOR_COUNT && count <= STORAGE_SECTOR_COUNT - sector;
}
#endif
