name: Build unstable

on: 
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name to generate (DO NOT USE vX.X.X!!!)"
        default: "continuous"
        required: true
      CFLAGS:
        description: "Optional GCC flags (-D)"
        default: ""
        required: false
      
jobs:
  build:
    name: BACCAble unstable
    runs-on: ubuntu-latest
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - run: arm-none-eabi-gcc --version

      - name: Clone
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Set CFLAGS
        run: |
          echo "CFLAGS=${{github.event.inputs.CFLAGS}}" >> $GITHUB_ENV

      - name: Echo GITHUB_ENV
        run: echo ${{ env.CFLAGS }}

      - name: Compile BH
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS='${{ env.CFLAGS }} -DBUILD_VERSION=\"${{ env.COMMIT_SHORT_SHA }}\" -DRELEASE_FLAVOR=BH_FLAVOR -DBH_FLAVOR=1' make all
          cp build/baccable-*.elf baccableBH_unstable.elf
          
      - name: Compile C1 Diesel
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS='${{ env.CFLAGS }} -DBUILD_VERSION=\"${{ env.COMMIT_SHORT_SHA }}\" -DRELEASE_FLAVOR=C1_FLAVOR -DC1_FLAVOR=1' make clean all
          cp build/baccable-*.elf baccableC1diesel_unstable.elf

      - name: Compile C1 Gasoline
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS='${{ env.CFLAGS }} -DBUILD_VERSION=\"${{ env.COMMIT_SHORT_SHA }}\" -DRELEASE_FLAVOR=C1_FLAVOR -DIS_GASOLINE -DC1_FLAVOR=1' make clean all
          cp build/baccable-*.elf baccableC1gasoline_unstable.elf

      - name: Compile C2
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS='${{ env.CFLAGS }} -DBUILD_VERSION=\"${{ env.COMMIT_SHORT_SHA }}\" -DRELEASE_FLAVOR=C2_FLAVOR -DC2_FLAVOR=1' make clean all
          cp build/baccable-*.elf baccableC2_unstable.elf

      - name: Compile CANable
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS='${{ env.CFLAGS }} -DBUILD_VERSION=\"${{ env.COMMIT_SHORT_SHA }}\" -DRELEASE_FLAVOR=CAN_FLAVOR -DCAN_FLAVOR=1' make clean all
          cp build/baccable-*.elf baccableCANable_unstable.elf
 
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: ${{github.event.inputs.TAG_NAME}}
          name: Unstable ${{ env.COMMIT_SHORT_SHA }}
          files: |
            ./firmware/ledsStripController/baccableBH_unstable.elf
            ./firmware/ledsStripController/baccableC1diesel_unstable.elf
            ./firmware/ledsStripController/baccableC1gasoline_unstable.elf
            ./firmware/ledsStripController/baccableC2_unstable.elf
            ./firmware/ledsStripController/baccableCANable_unstable.elf
