name: Build stable 

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    name: BACCAble stable
    runs-on: ubuntu-latest

    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1

      - run: arm-none-eabi-gcc --version

      - name: Clone
        uses: actions/checkout@v3

      - name: Compile BH
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS="-DRELEASE_FLAVOR=BH_FLAVOR -DBH_FLAVOR=1" make all
          cp build/baccable-*.elf baccableBH_stable_${{ github.ref_name }}.elf
          
      - name: Compile C1 Diesel
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS="-DRELEASE_FLAVOR=C1_FLAVOR -DC1_FLAVOR=1" make clean all
          cp build/baccable-*.elf baccableC1diesel_stable_${{ github.ref_name }}.elf

      - name: Compile C1 Gasoline
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS="-DRELEASE_FLAVOR=C1_FLAVOR -DIS_GASOLINE -DC1_FLAVOR=1" make clean all
          cp build/baccable-*.elf baccableC1gasoline_stable_${{ github.ref_name }}.elf

      - name: Compile C2
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS="-DRELEASE_FLAVOR=C2_FLAVOR -DC2_FLAVOR=1" make clean all
          cp build/baccable-*.elf baccableC2_stable_${{ github.ref_name }}.elf

      - name: Compile CANable
        working-directory: ./firmware/ledsStripController
        run: |
          CFLAGS="-DRELEASE_FLAVOR=CAN_FLAVOR -DCAN_FLAVOR=1" make clean all
          cp build/baccable-*.elf baccableCANable_stable_${{ github.ref_name }}.elf
 
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: |
            ./firmware/ledsStripController/baccableBH_stable_${{ github.ref_name }}.elf
            ./firmware/ledsStripController/baccableC1diesel_stable_${{ github.ref_name }}.elf
            ./firmware/ledsStripController/baccableC1gasoline_stable_${{ github.ref_name }}.elf
            ./firmware/ledsStripController/baccableC2_stable_${{ github.ref_name }}.elf
            ./firmware/ledsStripController/baccableCANable_stable_${{ github.ref_name }}.elf
